export const listAdditionalSkill = [
  {
    type: 6409,
    name: "365 Offices",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6159,
    name: "Adaptability",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6379,
    name: "Airflow",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6287,
    name: "Analysis",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6438,
    name: "AngularJS",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6288,
    name: "Ant",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6289,
    name: "Apache",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6411,
    name: "API testing",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6290,
    name: "APNs",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6386,
    name: "ARIMAX",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6291,
    name: "Auth0",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6292,
    name: "Auto Mapper",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6293,
    name: "AutoDesk,Revit",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6294,
    name: "AWS",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6295,
    name: "Azure Cloud",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6423,
    name: "Azure DevOps",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6296,
    name: "Azure Service Bus",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6298,
    name: "Babel",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6385,
    name: "BeautifulSoup",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6449,
    name: "betting",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6377,
    name: "BigQuery",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6309,
    name: "Bootstrap",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6299,
    name: "Centos",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6300,
    name: "Chakra UI",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6301,
    name: "CI/CD Pipelines",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6302,
    name: "CI/CD using Jenkins",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6400,
    name: "Clickup",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6390,
    name: "CNN",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6303,
    name: "Contenful",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6304,
    name: "CosmosDb",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6383,
    name: "Crawling data",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6305,
    name: "Creativity",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6448,
    name: "crypto-payment",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6306,
    name: "CSS3",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6447,
    name: "custodian platform",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6307,
    name: "Customer Service",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6308,
    name: "Dapper",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6422,
    name: "Data warehouse",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6370,
    name: "DBeaver",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6286,
    name: "Decision Making",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6394,
    name: "Deep Learning",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6285,
    name: "Dependency Injection",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6284,
    name: "Design Patterns",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6283,
    name: "Docker",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6262,
    name: "Documentation",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6401,
    name: "Draw.io",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6368,
    name: "E-commerce",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6450,
    name: "ECR",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6437,
    name: "Elasticsearch",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6263,
    name: "Electron",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6372,
    name: "Email Marketing",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6264,
    name: "Entity Framework",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6427,
    name: "ETL",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6433,
    name: "ETL Data Pipeline",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6265,
    name: "ExpressJS",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6445,
    name: "Extension (browser)",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6382,
    name: "FastAPI",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6406,
    name: "Figma",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6266,
    name: "Firebase",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6389,
    name: "GCP",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6463,
    name: "GIS-Geographic Infor sys",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6424,
    name: "GitLab",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6434,
    name: "Gogin",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6452,
    name: "go-kit",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6435,
    name: "Go-Micro",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6428,
    name: "Google Cloud BigQuery",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6369,
    name: "Google Shopping",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6436,
    name: "Gorm",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6454,
    name: "Grafana",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6267,
    name: "GraphQL",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6451,
    name: "gRPC",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6268,
    name: "GUI programming",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6420,
    name: "Hadoop",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6269,
    name: "Hangfire",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6421,
    name: "HDFS",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6270,
    name: "HTML5",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6271,
    name: "Identity Server",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6272,
    name: "IIS",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6273,
    name: "Integration Testing",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6274,
    name: "Ionic",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6275,
    name: "Java Spring",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6276,
    name: "Jenkins",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6398,
    name: "Jira",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6277,
    name: "JSON",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6278,
    name: "Jst",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6441,
    name: "Kafka",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6388,
    name: "KMeans",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6279,
    name: "Kubernetes",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6460,
    name: "LINE Pay",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6280,
    name: "LINQ",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6281,
    name: "Linux",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6432,
    name: "Logistic Regression",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6282,
    name: "LoopbackJs",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6391,
    name: "LSTM",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6402,
    name: "LucidChart",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6393,
    name: "Machine Learning",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6297,
    name: "Magento",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6310,
    name: "Material Design",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6431,
    name: "Matplotlib",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6311,
    name: "MediatR",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6440,
    name: "Message Broker",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6312,
    name: "Microservices",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6429,
    name: "Microsoft Power Apps",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6339,
    name: "Migrating app from .Net framework to .Net core 3.0",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6404,
    name: "Mind mapping",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6403,
    name: "Miro",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6340,
    name: "Mobile Application (React Native)",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6341,
    name: "MongoDB",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6342,
    name: "MS ACCESS",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6343,
    name: "MS SQL Server",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6344,
    name: "MUI",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6345,
    name: "Multi-threaded programming",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6378,
    name: "MySQL",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6346,
    name: "Nancy",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6347,
    name: "NextJs",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6348,
    name: "Nginx",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6350,
    name: "NgRx",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6361,
    name: "NoSQL database: Redis",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6455,
    name: "OAuth",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6351,
    name: "Object-Oriented Programming (OOP)",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6408,
    name: "Odoo ERP",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6352,
    name: "Openshift",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6419,
    name: "Oracle DB",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6430,
    name: "Pandas",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6457,
    name: "Payment",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6353,
    name: "PostgreSQL",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6413,
    name: "Postman",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6375,
    name: "PowerBI",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6354,
    name: "Problem Solving",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6381,
    name: "PySpark",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6380,
    name: "Pytorch",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6355,
    name: "Quartz.NET",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6356,
    name: "RabbitMQ",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6357,
    name: "Razor Pages",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6358,
    name: "React Toolkit",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6359,
    name: "Realm",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6360,
    name: "Redis",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6338,
    name: "Redux-Saga",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6349,
    name: "Redux-thunk",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6337,
    name: "Research",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6323,
    name: "RESTful APIs",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6313,
    name: "RESTful Web API",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6392,
    name: "RNN",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6439,
    name: "RxJS",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6314,
    name: "S3",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6446,
    name: "Scala",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6315,
    name: "Script",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6316,
    name: "SCSS",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6384,
    name: "Selenium",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6317,
    name: "Signal",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6318,
    name: "SignalR",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6319,
    name: "Single Page Application (Web-based)",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6468,
    name: "Sitecore",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6374,
    name: "Smart Contract",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6412,
    name: "SoapUI",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6320,
    name: "SOLID Principle",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6373,
    name: "Solidity",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6321,
    name: "SQL Query",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6322,
    name: "SQLite",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6324,
    name: "StrapiJs",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6335,
    name: "Stripe",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6325,
    name: "Styled components",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6326,
    name: "Symphony",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6327,
    name: "System Analysis and Design",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6376,
    name: "Tableau",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6328,
    name: "TailwindCSS",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6329,
    name: "Time Management",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6371,
    name: "Tools",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6453,
    name: "Traefik",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6399,
    name: "Trello",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6330,
    name: "TypeScript",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6467,
    name: "Umbraco",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6331,
    name: "Unit test (NUnit, Moq)",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6332,
    name: "Unit Testing",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6407,
    name: "Visily",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6333,
    name: "VNPay",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6334,
    name: "Webpack",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6261,
    name: "Windows Server",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6260,
    name: "Wireframe/Mockup",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6259,
    name: "WPF",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6387,
    name: "XGBoost",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6208,
    name: "XPI, XEC tokens",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6185,
    name: "XUnit",
    group: 9,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
];

export const listBusinessDomain = [
  {
    type: 6243,
    name: "3D Printing",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6181,
    name: "Aerospace & Aviation",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6173,
    name: "Agriculture",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6210,
    name: "AI & Machine Learning",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6255,
    name: "AI in Healthcare",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6174,
    name: "Architecture & Design",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6182,
    name: "Automotive",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6225,
    name: "Autonomous Vehicles",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6186,
    name: "Banking",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6212,
    name: "Beauty & Cosmetics",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6227,
    name: "Biohacking",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6175,
    name: "Biotechnology",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6187,
    name: "Blockchain",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6396,
    name: "Booking",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6417,
    name: "Calling",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6176,
    name: "Chemicals",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6213,
    name: "Childcare & Early Education",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6214,
    name: "Clean Energy & Renewables",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6235,
    name: "Clean Water",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6336,
    name: "Climate Technology",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6466,
    name: "CMS",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6160,
    name: "Construction & Engineering",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6177,
    name: "Consulting",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6178,
    name: "Consumer Electronics",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6247,
    name: "Cryptocurrency",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6443,
    name: "Cyber Security",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6236,
    name: "Cybersecurity",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6215,
    name: "Data & Analytics",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6188,
    name: "Dating",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6179,
    name: "Defense & Military",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6458,
    name: "Delivery System",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6232,
    name: "Digital Marketing",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6248,
    name: "Disaster Recovery",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6444,
    name: "Dropshipping",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6395,
    name: "Ecommerce",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6189,
    name: "E-commerce",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6190,
    name: "Education",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6251,
    name: "Edutainment",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6257,
    name: "Elderly Care",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6397,
    name: "E-learning",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6253,
    name: "Electric Vehicles",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6161,
    name: "Energy & Utilities",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6162,
    name: "Entertainment & Media",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6163,
    name: "Environmental Services",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6462,
    name: "ERP",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6216,
    name: "Event Management",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6164,
    name: "Fashion & Apparel",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6192,
    name: "Finance",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6425,
    name: "Financial",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6365,
    name: "Fintech",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6418,
    name: "Fleet Management",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6193,
    name: "FMCG",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6191,
    name: "Food & Beverage (F&B)",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6461,
    name: "Game",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6194,
    name: "Gaming",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6195,
    name: "Genetic Engineering",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6258,
    name: "Gig Economy",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6165,
    name: "Government & Public Sector",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6244,
    name: "Health Tech",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6196,
    name: "Healthcare",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6249,
    name: "Home Automation",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6207,
    name: "Hospitality",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6217,
    name: "HR & Talent Management",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6410,
    name: "HRM",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6197,
    name: "Industrial Automation",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6198,
    name: "Industrial Engineering",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6199,
    name: "Insurance",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6366,
    name: "Investment",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6237,
    name: "IoT",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6200,
    name: "IT Services",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6367,
    name: "KYC/AML",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6166,
    name: "Legal Services",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6201,
    name: "Logistics",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6442,
    name: "Lotto game",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6414,
    name: "Loyalty App",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6167,
    name: "Manufacturing",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6202,
    name: "Marketing & Advertising",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6209,
    name: "Mental Health",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6426,
    name: "Multimedia",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6218,
    name: "Music & Performing Arts",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6226,
    name: "Nanomedicine",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6241,
    name: "Nanotechnology",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6168,
    name: "Non-Profit & Charity",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6362,
    name: "Ocean Conservation",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6203,
    name: "Offshoring Service",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6180,
    name: "Online Education",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6459,
    name: "Payment",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6219,
    name: "Personal Development",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6252,
    name: "Personal Finance",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6233,
    name: "Personalized Medicine",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6230,
    name: "Personalized Nutrition",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6204,
    name: "Pharmaceuticals",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6205,
    name: "POS",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6224,
    name: "Quantum Cryptography",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6183,
    name: "Real Estate",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6206,
    name: "Recruitment",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6254,
    name: "Remote Work",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6246,
    name: "Renewable Energy",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6169,
    name: "Retail",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6238,
    name: "Robotics & Automation",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6245,
    name: "Smart Cities",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6456,
    name: "Smartwatches",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6416,
    name: "Social App",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6250,
    name: "Social Networking",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6220,
    name: "Social Services",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6405,
    name: "Solicitor (Law)",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6240,
    name: "Space Exploration",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6231,
    name: "Space Mining",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6228,
    name: "Space Tourism",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6170,
    name: "Sports & Fitness",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6211,
    name: "Supply Chain Management",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6229,
    name: "Sustainable Agriculture",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6234,
    name: "Sustainable Fashion",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6242,
    name: "Sustainable Tech",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6184,
    name: "Telecommunications",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6223,
    name: "Telemedicine",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6171,
    name: "Travel & Tourism",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6172,
    name: "Veterinary & Animal Care",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6256,
    name: "Virtual Events",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6415,
    name: "VPN/Proxy",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6239,
    name: "VR",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6221,
    name: "Wedding & Event Services",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
  {
    type: 6222,
    name: "Yoga & Wellness",
    group: 10,
    description: null,
    isOutdated: false,
    subOfDepartments: null,
  },
];

export const listProficiencySkillType = [
  { type: 1, name: "Beginner" },
  { type: 2, name: "Intermediate" },
  { type: 3, name: "Advanced" },
];

export const API = {
  GET_EMPLOYEE_LIST: "/api/employees",
  ADD_ADDITIONAL_SKILL: "/api/additional-skills",
  DELETE_ADDTIONAL_SKILL: "/api/additional-skills",
  ADD_BUSINESS_DOMAIN: "/api/business-domains",
  DELETE_BUSINESS_DOMAIN: "/api/business-domains",
};

export const TYPE = {
  ADDITIONAL_SKILL: 0,
  BUSINESS_DOMAIN: 1,
};
